// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LtZAPzncbh81D2cfEaULtWe0BsYsO9w',
    appId: '1:800742020260:web:a8d4158a6dbb0e94850231',
    messagingSenderId: '800742020260',
    projectId: 'glitchdex-app',
    authDomain: 'glitchdex-app.firebaseapp.com',
    storageBucket: 'glitchdex-app.firebasestorage.app',
    measurementId: 'G-7VPCYFLTLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIvz4kMaa47t1aZpO-_cp5642e3ZAZok',
    appId: '1:800742020260:android:d68f67820e0ddd6b850231',
    messagingSenderId: '800742020260',
    projectId: 'glitchdex-app',
    storageBucket: 'glitchdex-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTklBVs6dmupa3p9lgx0BYUO-FiVedzs',
    appId: '1:800742020260:ios:88e6014af3cd4553850231',
    messagingSenderId: '800742020260',
    projectId: 'glitchdex-app',
    storageBucket: 'glitchdex-app.firebasestorage.app',
    iosBundleId: 'com.example.glitchDex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTklBVs6dmupa3p9lgx0BYUO-FiVedzs',
    appId: '1:800742020260:ios:88e6014af3cd4553850231',
    messagingSenderId: '800742020260',
    projectId: 'glitchdex-app',
    storageBucket: 'glitchdex-app.firebasestorage.app',
    iosBundleId: 'com.example.glitchDex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-LtZAPzncbh81D2cfEaULtWe0BsYsO9w',
    appId: '1:800742020260:web:6b7364ed142576f3850231',
    messagingSenderId: '800742020260',
    projectId: 'glitchdex-app',
    authDomain: 'glitchdex-app.firebaseapp.com',
    storageBucket: 'glitchdex-app.firebasestorage.app',
    measurementId: 'G-2KSM7NM1KH',
  );
}
